# Generated by Django 5.2.11 on 2026-09-29 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0019_detectionevent_video'),
        ('person_journey', '0003_separate_tracklet_and_person_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraTopologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical_min_sec', models.PositiveIntegerField(default=5)),
                ('typical_max_sec', models.PositiveIntegerField(default=60)),
                ('hard_max_sec', models.PositiveIntegerField(default=180)),
                ('expected_exit_direction', models.CharField(blank=True, default='', max_length=32)),
                ('expected_entry_direction', models.CharField(blank=True, default='', max_length=32)),
                ('from_exit_zone', models.CharField(blank=True, default='', max_length=64)),
                ('to_entry_zone', models.CharField(blank=True, default='', max_length=64)),
                ('bidirectional', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PersonObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('face', 'Face'), ('reid', 'Body ReID'), ('appearance', 'Appearance')], db_index=True, max_length=16)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('quality', models.FloatField(default=0.5)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=512)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('travel_time_sec', models.FloatField(blank=True, null=True)),
                ('reid_score', models.FloatField(blank=True, null=True)),
                ('face_score', models.FloatField(blank=True, null=True)),
                ('appearance_score', models.FloatField(blank=True, null=True)),
                ('direction_score', models.FloatField(blank=True, null=True)),
                ('topology_score', models.FloatField(blank=True, null=True)),
                ('time_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, default='match', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='cameratrack',
            new_name='person_jour_trackle_798b19_idx',
            old_name='person_jour_trackle_idx',
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='end_bbox',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='entry_zone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='exit_zone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='movement_direction',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='start_bbox',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cameratrack',
            name='trajectory',
            field=models.JSONField(blank=True, default=list, help_text='Recent bbox centers / boxes for direction estimation.'),
        ),
        migrations.AddField(
            model_name='journeyperson',
            name='identity_state',
            field=models.CharField(choices=[('new', 'New'), ('tracking', 'Tracking'), ('candidate_match', 'Candidate Match'), ('confirmed', 'Confirmed'), ('continuous', 'Continuous Tracking'), ('occluded', 'Occluded'), ('reidentification', 'Re-identification'), ('transition', 'Camera Transition'), ('exited', 'Exited')], db_index=True, default='new', help_text='Lifecycle state machine for the global person.', max_length=24),
        ),
        migrations.AlterField(
            model_name='cameratrack',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('occluded', 'Occluded')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='cameratopologyedge',
            name='from_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_out', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='cameratopologyedge',
            name='to_camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_in', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='personobservation',
            name='journey_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='person_journey.journeyperson'),
        ),
        migrations.AddField(
            model_name='personobservation',
            name='tracklet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='person_journey.cameratrack'),
        ),
        migrations.AddField(
            model_name='persontransition',
            name='from_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='persontransition',
            name='from_tracklet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='person_journey.cameratrack'),
        ),
        migrations.AddField(
            model_name='persontransition',
            name='journey_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='person_journey.journeyperson'),
        ),
        migrations.AddField(
            model_name='persontransition',
            name='to_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='persontransition',
            name='to_tracklet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='person_journey.cameratrack'),
        ),
        migrations.AddIndex(
            model_name='cameratopologyedge',
            index=models.Index(fields=['from_camera', 'to_camera', 'is_active'], name='person_jour_from_ca_0e9b7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cameratopologyedge',
            unique_together={('from_camera', 'to_camera')},
        ),
        migrations.AddIndex(
            model_name='personobservation',
            index=models.Index(fields=['journey_person', 'kind', '-captured_at'], name='person_jour_journey_b1bad2_idx'),
        ),
        migrations.AddIndex(
            model_name='personobservation',
            index=models.Index(fields=['tracklet', 'kind', '-captured_at'], name='person_jour_trackle_4bf1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='persontransition',
            index=models.Index(fields=['journey_person', '-created_at'], name='person_jour_journey_6d263a_idx'),
        ),
    ]
