# Generated by Django 5.2.11 on 2026-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_journey', '0004_journey_gallery_topology_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameratrack',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
