# Generated by Django 5.2.14 on 2026-09-01 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecoveryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('original_file', models.FileField(upload_to='video_recovery/uploads/%Y/%m/%d/')),
                ('recovered_file', models.FileField(blank=True, upload_to='video_recovery/recovered/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('current_stage', models.CharField(choices=[('upload', 'Video Upload'), ('forensic', 'File Forensic Analyzer'), ('container', 'Container Recovery'), ('stream', 'Stream Analysis'), ('frames', 'Frame Recovery Engine'), ('valid_frames', 'Valid Frame Processing'), ('bad_frames', 'Bad Frame Restoration'), ('missing_frames', 'Missing Frame Generation'), ('temporal', 'Temporal Consistency AI'), ('audio', 'Audio Recovery'), ('reconstruct', 'Video Reconstruction'), ('validate', 'Quality Validation'), ('completed', 'Recovered Video')], default='upload', max_length=32)),
                ('stage_logs', models.JSONField(blank=True, default=list)),
                ('forensic_report', models.JSONField(blank=True, default=dict)),
                ('quality_report', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_recovery_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
