# Generated by Django 5.2.14 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecoveryjob',
            name='damage_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='videorecoveryjob',
            name='hybrid_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='videorecoveryjob',
            name='original_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='videorecoveryjob',
            name='preserved_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='videorecoveryjob',
            name='current_stage',
            field=models.CharField(choices=[('upload', 'Video Upload'), ('validate_upload', 'Upload Validation'), ('preserve', 'Preserve Original'), ('damage_analysis', 'Deep Damage Analysis'), ('damage_map', 'Damage Map'), ('recovery', 'Recovery Engine'), ('regeneration', 'Regeneration Engine'), ('hybrid_merge', 'Hybrid Merger'), ('forensic', 'File Forensic Analyzer'), ('container', 'Container Recovery'), ('stream', 'Stream Analysis'), ('frames', 'Frame Recovery Engine'), ('valid_frames', 'Valid Frame Processing'), ('bad_frames', 'Bad Frame Restoration'), ('missing_frames', 'Missing Frame Generation'), ('temporal', 'Temporal Consistency AI'), ('audio', 'Audio Recovery'), ('reconstruct', 'Video Reconstruction'), ('validate', 'Quality Validation'), ('completed', 'Final Output')], default='upload', max_length=32),
        ),
    ]
