# Generated by Django 5.2.11 on 2026-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0017_detectionevent_infer_frame_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='health_roi',
            field=models.JSONField(blank=True, default=None, help_text='Optional health/visibility ROI: {x1,y1,x2,y2} normalized 0–1 or pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, default='3840x2160', max_length=32),
        ),
    ]
