# Generated by Django 5.2.11 on 2026-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_camera_health_and_roi'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['-created_at'], name='detev_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['camera', '-created_at'], name='detev_cam_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['is_alert', '-created_at'], name='detev_alert_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionevent',
            index=models.Index(fields=['class_name', '-created_at'], name='detev_class_created_idx'),
        ),
    ]
