# Generated by Django 5.2.11 on 2026-08-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_visitorface'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitorface',
            new_name='visitors_vi_visitor_f3333b_idx',
            old_name='visitors_vi_visitor_7a8c1e_idx',
        ),
    ]
