# Generated by Django 5.2.11 on 2026-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_rename_visitorface_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='department_to_visit',
            field=models.CharField(choices=[('hr', 'hr'), ('it', 'it'), ('finance', 'finance'), ('operations', 'operations'), ('marketing', 'marketing'), ('admin', 'admin'), ('enforcement', 'enforcement'), ('appraisement', 'appraisement')], max_length=20),
        ),
    ]
