# Generated by Django 5.2.11 on 2026-10-05 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0019_detectionevent_video'),
        ('infrastructure_monitoring', '0006_support_tickets_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLUTION_SUBMITTED', 'Resolution Submitted'), ('SUPPORT_VERIFIED', 'Support Verified'), ('PENDING_CLIENT_CONFIRM', 'Waiting Client'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=32)),
                ('priority', models.CharField(choices=[('P1', 'Critical (P1)'), ('P2', 'High (P2)'), ('P3', 'Medium (P3)'), ('P4', 'Low (P4)')], db_index=True, default='P3', max_length=8)),
                ('suggested_priority', models.CharField(choices=[('P1', 'Critical (P1)'), ('P2', 'High (P2)'), ('P3', 'Medium (P3)'), ('P4', 'Low (P4)')], default='P3', max_length=8)),
                ('category', models.CharField(choices=[('CAMERA', 'Camera'), ('NVR', 'NVR'), ('NETWORK', 'Network'), ('HARDWARE', 'Hardware'), ('SERVER', 'Server'), ('ACCESS', 'Access'), ('INFRASTRUCTURE', 'Infrastructure'), ('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('AI_ML', 'AI / ML'), ('API', 'API'), ('DATABASE', 'Database'), ('BUG', 'Bug'), ('FEATURE', 'Feature'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32)),
                ('suggested_category', models.CharField(choices=[('CAMERA', 'Camera'), ('NVR', 'NVR'), ('NETWORK', 'Network'), ('HARDWARE', 'Hardware'), ('SERVER', 'Server'), ('ACCESS', 'Access'), ('INFRASTRUCTURE', 'Infrastructure'), ('BACKEND', 'Backend'), ('FRONTEND', 'Frontend'), ('AI_ML', 'AI / ML'), ('API', 'API'), ('DATABASE', 'Database'), ('BUG', 'Bug'), ('FEATURE', 'Feature'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('DEVELOPER', 'Developer'), ('UNASSIGNED', 'Unassigned')], db_index=True, default='UNASSIGNED', max_length=16)),
                ('suggested_department', models.CharField(choices=[('IT', 'IT'), ('DEVELOPER', 'Developer'), ('UNASSIGNED', 'Unassigned')], default='UNASSIGNED', max_length=16)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('asset_label', models.CharField(blank=True, default='', max_length=200)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('client_notes', models.TextField(blank=True, default='')),
                ('sla_response_due', models.DateTimeField(blank=True, null=True)),
                ('sla_resolve_due', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='portal', help_text='portal | mobile | alert | admin', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('client_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='cameras.camera')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='requests_support.supportticket')),
                ('infra_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='infrastructure_monitoring.infradevice')),
                ('infra_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='infrastructure_monitoring.infrasite')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_reviewed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes hidden from the client requester.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests_support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requests_support.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'department'], name='requests_su_status_106f59_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='requests_su_status_e9d58e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['requester', 'status'], name='requests_su_request_2f9599_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='requests_su_assigne_db1eee_idx'),
        ),
    ]
