# Generated by Django 5.2.11 on 2026-10-05 07:07

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_expires_at(apps, schema_editor):
    SupportTicket = apps.get_model("requests_support", "SupportTicket")
    now = timezone.now()
    for ticket in SupportTicket.objects.filter(expires_at__isnull=True).iterator():
        created = ticket.created_at or now
        ticket.expires_at = created + timedelta(hours=24)
        ticket.save(update_fields=["expires_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0019_detectionevent_video'),
        ('infrastructure_monitoring', '0006_support_tickets_and_roles'),
        ('requests_support', '0001_support_tickets_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Ticket validity window end (default 24 hours from creation).', null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLUTION_SUBMITTED', 'Resolution Submitted'), ('SUPPORT_VERIFIED', 'Support Verified'), ('PENDING_CLIENT_CONFIRM', 'Waiting Client'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='NEW', max_length=32),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['expires_at', 'status'], name='requests_su_expires_bb755f_idx'),
        ),
        migrations.RunPython(backfill_expires_at, migrations.RunPython.noop),
    ]
