# Generated by Django 5.2.11 on 2026-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_support', '0002_ticket_validity_24h_and_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_chat/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
