# Generated by Django 5.2.11 on 2026-09-17 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0018_camera_health_and_roi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('brightness', models.FloatField(default=0)),
                ('contrast', models.FloatField(default=0)),
                ('sharpness', models.FloatField(default=0)),
                ('noise', models.FloatField(default=0)),
                ('exposure', models.FloatField(default=0, help_text='Mean brightness proxy')),
                ('glare', models.FloatField(default=0)),
                ('dark_ratio', models.FloatField(default=0)),
                ('bright_ratio', models.FloatField(default=0)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('freeze_score', models.FloatField(default=0)),
                ('stream_latency', models.FloatField(blank=True, null=True)),
                ('rtsp_available', models.BooleanField(default=True)),
                ('person_visibility', models.FloatField(default=0)),
                ('vehicle_visibility', models.FloatField(default=0)),
                ('plate_visibility', models.FloatField(default=0)),
                ('face_visibility', models.FloatField(default=0)),
                ('obstruction_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('critical', 'Critical'), ('offline', 'Offline'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('image_score', models.FloatField(default=0)),
                ('stream_score', models.FloatField(default=0)),
                ('visibility_score', models.FloatField(default=0)),
                ('fingerprint', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CameraHealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('message', models.CharField(max_length=512)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='cameras.camera')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='camera_health.camerahealthsnapshot')),
            ],
            options={
                'ordering': ['-last_detected'],
            },
        ),
        migrations.AddIndex(
            model_name='camerahealthsnapshot',
            index=models.Index(fields=['camera', '-timestamp'], name='camera_heal_camera__341857_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthsnapshot',
            index=models.Index(fields=['status', '-timestamp'], name='camera_heal_status_bf8712_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthalert',
            index=models.Index(fields=['camera', 'resolved', '-last_detected'], name='camera_heal_camera__155fed_idx'),
        ),
        migrations.AddIndex(
            model_name='camerahealthalert',
            index=models.Index(fields=['alert_type', 'resolved'], name='camera_heal_alert_t_63a1c0_idx'),
        ),
    ]
