# Generated by Django 5.2.14 on 2026-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officergpshistory',
            name='altitude_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='heading_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpslatest',
            name='altitude_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpslatest',
            name='heading_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpslatest',
            name='speed_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
