# Generated by Django 5.2.11 on 2026-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_tracking', '0002_gps_motion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='officergpshistory',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='device_uuid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='event_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='server_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officergpshistory',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
