# Generated by Django 5.2.11 on 2026-09-18 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_mobilephonesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOGGED_OUT', 'Logged out'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('STALE', 'Stale')], db_index=True, default='ACTIVE', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_gps_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_access_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mobilephonesession',
            name='access_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lock_sessions', to='logs.mobileaccesssession'),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('platform', models.CharField(blank=True, default='', max_length=40)),
                ('browser', models.CharField(blank=True, default='', max_length=80)),
                ('os_version', models.CharField(blank=True, default='', max_length=80)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('pwa_version', models.CharField(blank=True, default='', max_length=40)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('mobile_access_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale'), ('OFFLINE', 'Offline'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_gps_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_accuracy', models.FloatField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_gps_status', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=48)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_mobile_alerts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='logs.mobileaccesssession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='logs.mobiledevice')),
            ],
        ),
        migrations.AddField(
            model_name='mobileaccesssession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='logs.mobiledevice'),
        ),
        migrations.AddField(
            model_name='mobilephonesession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lock_sessions', to='logs.mobiledevice'),
        ),
        migrations.CreateModel(
            name='MobileEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_event_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', '-last_seen_at'], name='logs_mobile_user_id_e16019_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['is_revoked', 'is_active'], name='logs_mobile_is_revo_8a4a02_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilealert',
            index=models.Index(fields=['user', 'alert_type', 'is_active'], name='logs_mobile_user_id_507916_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilealert',
            index=models.Index(fields=['-detected_at'], name='logs_mobile_detecte_9386d6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileaccesssession',
            index=models.Index(fields=['user', 'status'], name='logs_mobile_user_id_a9c1de_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileaccesssession',
            index=models.Index(fields=['device', 'status'], name='logs_mobile_device__ef30ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobileaccesssession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('device',), name='uniq_active_mobile_access_session_per_device'),
        ),
    ]
