# Generated by Django 5.2.11 on 2026-09-20 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_ciis_mobile_enforcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['-time'], name='logs_userac_time_0a214f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-time'], name='logs_userac_user_id_27384c_idx'),
        ),
    ]
