# Generated by Django 5.2.14 on 2026-08-04 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name e.g. Peshawar HQ', max_length=150)),
                ('location_code', models.CharField(blank=True, default='', help_text='Optional site code e.g. PESHAWAR', max_length=64)),
                ('base_url', models.URLField(help_text='Django API root e.g. https://192.168.1.50:8000', max_length=500)),
                ('ml_base_url', models.URLField(blank=True, default='', help_text='ML service root for live MJPEG. Blank = same host as base_url with /ml proxy, or :8100.', max_length=500)),
                ('auth_token', models.CharField(help_text='DRF Token for the remote server (Authorization: Token …)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_health', models.CharField(blank=True, default='', max_length=32)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_servers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_central_remote_server',
                'ordering': ['name'],
            },
        ),
    ]
