# Generated by Django 5.2.14 on 2026-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteserver',
            name='connection_mode',
            field=models.CharField(choices=[('ml', 'ML service only'), ('django', 'Full Tekeye (Django + ML)')], default='ml', help_text='ml = cameras from that ML /live/status; django = full remote API', max_length=16),
        ),
        migrations.AlterField(
            model_name='remoteserver',
            name='auth_token',
            field=models.CharField(blank=True, default='', help_text='DRF Token for remote Django (django mode). Unused for ml mode.', max_length=255),
        ),
        migrations.AlterField(
            model_name='remoteserver',
            name='base_url',
            field=models.URLField(blank=True, default='', help_text='Django API root (django mode). Optional in ml mode.', max_length=500),
        ),
        migrations.AlterField(
            model_name='remoteserver',
            name='location_code',
            field=models.CharField(blank=True, default='', help_text='Optional site code e.g. DI_KHAN', max_length=64),
        ),
        migrations.AlterField(
            model_name='remoteserver',
            name='ml_base_url',
            field=models.URLField(blank=True, default='', help_text='ML service root e.g. http://192.168.199.12:8100', max_length=500),
        ),
        migrations.AlterField(
            model_name='remoteserver',
            name='name',
            field=models.CharField(help_text='Display name e.g. DI Khan ML', max_length=150),
        ),
    ]
