# Generated by Django 5.2.14 on 2026-08-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_central', '0002_connection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteserver',
            name='cached_cameras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='remoteserver',
            name='cameras_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
