# Generated by Django 5.2.14 on 2026-08-27 04:38

import seizure_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seizure_management', '0017_drop_char_length_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detentionassessment',
            name='document_relevance',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Relevant', 'Relevant'), ('Not Relevant', 'Not Relevant')], db_index=True, default='Pending'),
        ),
        migrations.AlterField(
            model_name='detentionassessment',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft'),
        ),
        migrations.AlterField(
            model_name='detentionassessmentattachment',
            name='file',
            field=models.FileField(max_length=1024, upload_to=seizure_management.models.assessment_attachment_path),
        ),
        migrations.AlterField(
            model_name='detentionassessmentattachment',
            name='file_type',
            field=models.TextField(choices=[('photo', 'Photo'), ('video', 'Video'), ('pdf', 'PDF'), ('invoice', 'Invoice'), ('delivery_challan', 'Delivery Challan'), ('import_document', 'Import Document'), ('cnic', 'CNIC'), ('other', 'Other')], default='other'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='priority',
            field=models.TextField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='recommendation',
            field=models.TextField(blank=True, choices=[('No Action', 'No Action'), ('Warning', 'Warning'), ('Further Investigation', 'Further Investigation'), ('Issue Detention Memo', 'Issue Detention Memo'), ('Release Goods', 'Release Goods')], default='Issue Detention Memo'),
        ),
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft'),
        ),
        migrations.AlterField(
            model_name='notesheetattachment',
            name='file',
            field=models.FileField(max_length=1024, upload_to=seizure_management.models.note_sheet_attachment_path),
        ),
        migrations.AlterField(
            model_name='notesheetattachment',
            name='file_type',
            field=models.TextField(choices=[('photo', 'Photo'), ('video', 'Video'), ('pdf', 'PDF'), ('invoice', 'Invoice'), ('delivery_challan', 'Delivery Challan'), ('import_document', 'Import Document'), ('cnic', 'CNIC'), ('other', 'Other')], default='other'),
        ),
        migrations.AlterField(
            model_name='notesheetitemimage',
            name='image',
            field=models.FileField(max_length=1024, upload_to=seizure_management.models.note_sheet_item_image_path),
        ),
        migrations.AlterField(
            model_name='recoverymemo',
            name='approval_status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Draft'),
        ),
        migrations.AlterField(
            model_name='recoverymemo',
            name='category',
            field=models.TextField(choices=[('Dangerous/Chemical', 'Dangerous/Chemical'), ('Perishable', 'Perishable'), ('Other', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='seizurereport',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted')], default='Draft'),
        ),
    ]
