# Generated by Django 5.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0017_detectionevent_infer_frame_size"),
        ("seizure_management", "0018_drop_remaining_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="notesheetitem",
            name="detected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the item was detected or found at the located camera.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notesheetitem",
            name="detection_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional AI DetectionEvent that sourced this goods line.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="note_sheet_goods_lines",
                to="cameras.detectionevent",
            ),
        ),
        migrations.AddField(
            model_name="notesheetitem",
            name="located_camera",
            field=models.ForeignKey(
                blank=True,
                help_text="Camera where this note-sheet item was located/detected.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="note_sheet_goods",
                to="cameras.camera",
            ),
        ),
    ]
