# Generated by Django 5.2.14 on 2026-08-11 06:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0014_camera_model_purposes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('object_type', models.CharField(choices=[('person', 'Person'), ('vehicle', 'Vehicle'), ('object', 'Object')], db_index=True, default='object', max_length=16)),
                ('class_name', models.CharField(blank=True, default='', max_length=80)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('reid_embedding', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('entry_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('camera_history', models.JSONField(blank=True, default=list)),
                ('track_history', models.JSONField(blank=True, default=list)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=512)),
                ('first_detection_event_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_objects_latest', to='cameras.camera')),
            ],
            options={
                'ordering': ['-last_seen_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectCameraTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_track_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], db_index=True, default='active', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_bbox', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_tracks', to='cameras.camera')),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='object_tracking.globalobject')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='globalobject',
            index=models.Index(fields=['object_type', 'class_name', '-last_seen_at'], name='object_trac_object__f2ebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='objectcameratrack',
            index=models.Index(fields=['camera', 'local_track_id', 'status'], name='object_trac_camera__eb8696_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectcameratrack',
            constraint=models.UniqueConstraint(fields=('camera', 'local_track_id', 'started_at'), name='object_tracking_unique_cam_track_start'),
        ),
    ]
