# Generated by Django 5.2.14 on 2026-08-11 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_camera_model_purposes'),
        ('object_tracking', '0001_initial_global_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_track_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], db_index=True, default='active', max_length=16)),
                ('entry_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('exit_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('detection_event_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=512)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_visits', to='cameras.camera')),
                ('global_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='object_tracking.globalobject')),
            ],
            options={
                'ordering': ['-entry_at'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='object_trac_status_78ec8f_idx'), models.Index(fields=['global_object', '-entry_at'], name='object_trac_global__8aee13_idx')],
            },
        ),
    ]
