# Generated by Django 5.2.11 on 2026-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detentions', '0005_goodsline_located_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentionmemo',
            name='updated_by',
            field=models.TextField(blank=True, default=''),
        ),
    ]
