# Generated by Django 5.2.11 on 2026-09-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(blank=True, choices=[('camera', 'Camera'), ('nvr', 'NVR'), ('ups', 'UPS'), ('inverter', 'Inverter'), ('network', 'Network Device')], default='', help_text='Empty = all device types', max_length=16)),
                ('metric_key', models.CharField(help_text='e.g. battery_percent, offline, inverter_fault', max_length=64)),
                ('operator', models.CharField(default='lt', help_text='lt | lte | gt | gte | eq | neq', max_length=8)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('message_template', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('camera', 'Camera'), ('nvr', 'NVR'), ('ups', 'UPS'), ('inverter', 'Inverter'), ('network', 'Network Device')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model_number', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('install_location', models.CharField(blank=True, default='', help_text='Room, rack, or zone label', max_length=200)),
                ('primary_protocol', models.CharField(choices=[('none', 'None / Manual'), ('icmp', 'ICMP (Ping)'), ('snmp', 'SNMP'), ('modbus_tcp', 'Modbus TCP'), ('modbus_rtu', 'Modbus RTU'), ('onvif', 'ONVIF'), ('rtsp', 'RTSP'), ('http', 'HTTP API')], default='icmp', max_length=16)),
                ('secondary_protocol', models.CharField(blank=True, choices=[('none', 'None / Manual'), ('icmp', 'ICMP (Ping)'), ('snmp', 'SNMP'), ('modbus_tcp', 'Modbus TCP'), ('modbus_rtu', 'Modbus RTU'), ('onvif', 'ONVIF'), ('rtsp', 'RTSP'), ('http', 'HTTP API')], default='none', max_length=16)),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=256)),
                ('snmp_version', models.CharField(blank=True, choices=[('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=8)),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=128)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('snmp_oid_map', models.JSONField(blank=True, default=dict, help_text='Optional OID map, e.g. {"battery_percent": "1.3.6.1..."}')),
                ('modbus_unit_id', models.PositiveIntegerField(default=1)),
                ('modbus_port', models.PositiveIntegerField(default=502)),
                ('modbus_register_map', models.JSONField(blank=True, default=list, help_text='[{"name":"battery_soc","register":1003,"scale":0.1,"unit":"%"}]')),
                ('onvif_port', models.PositiveIntegerField(default=80)),
                ('rtsp_url', models.CharField(blank=True, default='', max_length=512)),
                ('channel_count', models.PositiveIntegerField(blank=True, help_text='NVR channel capacity', null=True)),
                ('supports_onvif', models.BooleanField(default=False)),
                ('supports_rtsp', models.BooleanField(default=True)),
                ('supports_snmp', models.BooleanField(default=False)),
                ('supports_modbus', models.BooleanField(default=False)),
                ('rated_capacity_kva', models.FloatField(blank=True, null=True)),
                ('rated_power_kw', models.FloatField(blank=True, null=True)),
                ('network_role', models.CharField(blank=True, default='', help_text='switch / router / firewall / ap', max_length=64)),
                ('poll_interval_sec', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded'), ('fault', 'Fault'), ('unknown', 'Unknown'), ('maintenance', 'Maintenance')], db_index=True, default='unknown', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=512)),
                ('last_metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InfraSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('actor', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='infrastructure_monitoring.infradevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='infradevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='infrastructure_monitoring.infrasite'),
        ),
        migrations.CreateModel(
            name='InfraAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('metric_key', models.CharField(blank=True, default='', max_length=64)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='infrastructure_monitoring.infradevice')),
            ],
            options={
                'ordering': ['-last_detected'],
                'indexes': [models.Index(fields=['resolved', 'severity', '-last_detected'], name='infrastruct_resolve_bda14f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='infradevice',
            index=models.Index(fields=['device_type', 'is_active'], name='infrastruct_device__d30bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='infradevice',
            index=models.Index(fields=['status', 'device_type'], name='infrastruct_status_584cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='infradevice',
            index=models.Index(fields=['ip_address'], name='infrastruct_ip_addr_1b8c29_idx'),
        ),
    ]
