# Generated by Django 5.2.11 on 2026-09-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infradevice',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infradevice',
            name='source_key',
            field=models.CharField(blank=True, help_text='External source identity for auto-synced devices', max_length=96, null=True, unique=True),
        ),
    ]
