# Generated by Django 5.2.11 on 2026-09-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring', '0002_infradevice_last_polled_at_infradevice_source_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraNvrLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(db_index=True)),
                ('major_type', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('subtype', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('channel_no', models.CharField(blank=True, default='', max_length=32)),
                ('local_remote_user', models.CharField(blank=True, default='', max_length=128)),
                ('remote_host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nvr_logs', to='infrastructure_monitoring.infradevice')),
            ],
            options={
                'ordering': ['-log_time', '-id'],
                'indexes': [models.Index(fields=['device', '-log_time'], name='infrastruct_device__282652_idx'), models.Index(fields=['device', 'major_type', '-log_time'], name='infrastruct_device__ab92b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'fingerprint'), name='uniq_infra_nvr_log_fingerprint')],
            },
        ),
    ]
