# Generated by Django 5.2.11 on 2026-10-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure_monitoring', '0005_infraserverlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='infraserverlog',
            new_name='infrastruct_device__e00dc6_idx',
            old_name='infrastruct_device__srvlog_idx',
        ),
        migrations.RenameIndex(
            model_name='infraserverlog',
            new_name='infrastruct_device__5d8f0b_idx',
            old_name='infrastruct_device__srvcat_idx',
        ),
    ]
