# Generated by Django 5.2.11 on 2026-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_attendance_insightface_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
