# Generated by Django 5.2.11 on 2026-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_swh_ratta_kulachi_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='video',
            field=models.FileField(blank=True, help_text='Deprecated: attendance proof is image-only; kept for old records.', null=True, upload_to='attendance/videos/'),
        ),
    ]
