# Generated by Django 5.2.11 on 2026-09-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_swh_ratta_kulachi_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='video',
            field=models.FileField(blank=True, help_text='Deprecated: attendance proof is image-only; kept for old records.', null=True, upload_to='attendance/videos/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
