# Generated by Django 5.2.11 on 2026-09-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_attendance_video'),
        ('users', '0025_staff_name_only_required'),
    ]

    operations = [
    ]
