# Generated by Django 5.2.11 on 2026-09-28 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Typo-tolerant search (word_similarity) for the agent.
        TrigramExtension(),
        migrations.AddField(
            model_name='voicesession',
            name='mode',
            field=models.CharField(choices=[('voice', 'Voice'), ('chat', 'Chat')], db_index=True, default='voice', max_length=8),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='voicesession',
            name='transcript',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='voice_agent.voicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
